[project]
name = "ai-tools"
version = "0.1.0"
description = "AI Tools for Izzaz"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-analytics-data>=0.18.18",
    "openai>=1.75.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pymongo>=4.12.0",
]
